site_name: JP Contents Hub
docs_dir: "content"
nav:
  - 日本語ワークショップ: index.md
theme:
  name: material
  features:
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
plugins:
  - search:
      separator: '[\s\-\.\,\(\)]+'
      lang:
        - en
        - ja
markdown_extensions:
  - meta
